default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: db_admin
  password: dbadmin123
  host: localhost

development:
  <<: *default
  database: hellorails_development

test:
  <<: *default
  database: hellorails_test

production:
  <<: *default
  database: hellorails_production
  username: hellorails
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
